language: go

go:
  - 1.11.x

os:
  - linux
  - linux-ppc64le
services:
  - docker

# Only build on master, stable branches and tag
# The stable branch and tag should be leading with numbers
branches:
  only:
    - master
    - development
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

before_install:
  # https://github.com/golang/dep/blob/master/docs/FAQ.md#how-do-i-get-dep-to-authenticate-via-ssh-to-a-git-repo
  - git config --global url."git@github.ibm.com:".insteadOf "https://github.ibm.com/"
  - source travis-env.sh
  - make init

install:
  - make deps

script:
  - make copyright-check lint test build docker:info docker:build

after_success:
  - test "$TRAVIS_EVENT_TYPE" = "pull_request" && make push

deploy:
  skip_cleanup: true
  provider: script
  script: make release
  on:
    all_branches: true

after_deploy:
  - |
      curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
      python travis_after_all.py https://travis.ibm.com/api
      export $(cat .to_export_back)
      if [[ "$BUILD_LEADER" == "YES" ]]; then
        if [[ "$BUILD_AGGREGATE_STATUS" == "others_succeeded" ]]; then
          echo "All jobs succeeded! Creating multi arch image..."
          make docker:manifest-tool docker:multi-arch
        else
          echo "Some jobs failed" && exit 1
        fi
      fi
